name: concurrency test

on:
  workflow_dispatch:
    inputs:
      time:
        description: time
        required: true
        type: input
        default: "60"

jobs:
  job10:
    runs-on: ubuntu-latest
    concurrency: 
      group: test
      cancel-in-progress: false
    steps:
      - name: echo
        run: |
          sleep ${{inputs.time}}
          echo hi
  job11:
    runs-on: ubuntu-latest
    needs: [job10]
    concurrency: 
      group: test
      cancel-in-progress: true
    steps:
      - name: echo
        run: |
          sleep ${{inputs.time}}
          echo hi
  job20:
    runs-on: ubuntu-latest
    concurrency: 
      group: test-1
      cancel-in-progress: true
    steps:
      - name: echo
        run: |
          sleep ${{inputs.time}}
          echo hi
  job21:
    runs-on: ubuntu-latest
    needs: [job20]
    concurrency: 
      group: test-1
      cancel-in-progress: false
    steps:
      - name: echo
        run: |
          sleep ${{inputs.time}}
          echo hi
  job30:
    runs-on: ubuntu-latest
    concurrency: 
      group: test-3
    steps:
      - name: echo
        run: |
          sleep ${{inputs.time}}
          echo hi

  job40:
    runs-on: ubuntu-latest
    concurrency: 
      group: test
      cancel-in-progress: true
    steps:
      - name: echo
        run: |
          sleep ${{inputs.time}}
          echo hi
  job41:
    runs-on: ubuntu-latest
    needs: [job40]
    concurrency: 
      group: test
      cancel-in-progress: true
    steps:
      - name: echo
        run: |
          sleep ${{inputs.time}}
          echo hi

  job50:
    runs-on: ubuntu-latest
    concurrency: 
      group: test
      cancel-in-progress: false
    steps:
      - name: echo
        run: |
          sleep ${{inputs.time}}
          echo hi
  job51:
    runs-on: ubuntu-latest
    needs: [job50]
    concurrency: 
      group: test
      cancel-in-progress: false
    steps:
      - name: echo
        run: |
          sleep ${{inputs.time}}
          echo hi
