on:
  repository_dispatch:
    types: [test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo ${{ github.event.client_payload }}
          echo '${{ github.event.client_payload }}' | jq -rc
          
          
