on:
  repository_dispatch:
    types: [test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo '${{ toJSON(github.event.client_payload) }}'
          echo '${{ toJSON(github.event.client_payload) }}' | jq -rc
          
          
