name: test

on:
  workflow_dispatch:
    inputs:
      env:
        description: env
        required: false
        type: input

jobs:
  jon1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo hi
  envjon:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: |
          echo ${{ secrets.COMMON }} | cut -c 1-2  > hoge.txt
          echo ${{ secrets.E_VALUE }} | cut -c 1-2 >> hoge.txt
          cat hoge.txt
      
  
