name: test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      env:
        description: env
        required: false
        type: input
permissions:
  contents: write 
  pull-requests: write

jobs:
  jon1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - uses: actions/checkout@v3
      - name: change
        run: |
          echo $(date) > date.txt
          
          echo "abc" >> label.txt
          echo "edf" >> label.txt
          echo "dfg" >> label.txt
          
          echo "+ 111" >> change.txt
          echo "+ 211" >> change.txt
          echo "+ 3333" >> change.txt
          
          echo 'CHANGE<<EOF' >> $GITHUB_ENV
          cat change.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo 'LABEL<<EOF' >> $GITHUB_ENV
          cat label.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: Update test
            title: Update test2
            delete-branch: true
            base: main
            labels: ${{ env.LABEL }}
            body: |
              - Dependency updates
              ${{ env.CHANGE }}
  
            branch: test/test12

      
  
