name: test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      env:
        description: env
        required: false
        type: input

jobs:
  jon1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo -${{ (1 == 1 && github.event.number ) || '' }}----
  envjon:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: |
          ./.github/test.sh
      
  
