name: test

on:
  workflow_dispatch:
    inputs:
      env:
        description: env
        required: true
        default: test
        type: choice
        options:
          - test
          - prod

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: |
          echo ${{ secrets.COMMON }}
          echo ${{ secrets.E_VALUE }}
      
  
