name: test2

on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: write 
  pull-requests: write

jobs:
  jon1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: Update test
            title: Update test3
            labels: hoge
            body: |
              - Dependency updates
  
            branch: branch3
