name: test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      env:
        description: env
        required: false
        type: input

jobs:
  jon1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: echo
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
          brew install suzuki-shunsuke/tfcmt/tfcmt
          brew install suzuki-shunsuke/github-comment/github-comment
          echo $PATH
          which tfcmt
          which github-comment
          

      
  
