name: test2

on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: write 
  pull-requests: write

jobs:
  jon1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: branch3
        fetch-depth: 0
    - name: Run the Action
      uses: devops-infra/action-pull-request@v0.5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: branch3
        target_branch: main
        title: My pull request
        body: "**Automated pull request**"
        label: enhancement
        get_diff: true
